[ADC 686]-testing for wp forms
adcaptcha-org/adCAPTCHA-wordpress-plugin pull request #70
Opened 2024-12-12 15:54 UTC by vasswann

Updated Forms PHP: Removed require_once in favor of Composer autoloader; refactored dependency injection by moving Verify instantiation to the constructor, enhancing testability, separation of concerns, and flexibility; updated tests and added a new helper function in test_helpers.php; WPForms testing is now complete.

2024-12-17 15:05 UTC, Lucasarenaterry requested changes

2024-12-18 09:27 UTC, vasswann commented on src/Plugin/WPForms/Forms.php
> +                // this line removed because it is using composer autoloader
WP forms tested and working after the require was removed

2025-01-06 09:50 UTC, Lucasarenaterry approved these changes

2025-01-06 10:48 UTC, MattGibney approved these changes

2025-01-07 08:46 UTC, merged