Added Github action to deploy plugin to Wordpress SVN
adcaptcha-org/adCAPTCHA-wordpress-plugin pull request #9
Opened 2024-02-12 12:54 UTC by Lucasarenaterry

2024-02-12 13:48 UTC, MattGibney requested changes

2024-02-12 13:48 UTC, MattGibney commented on .github/workflows/deployToWordPressSVN.yml
> +    name: New tag
Give this a name

2024-02-12 13:48 UTC, MattGibney commented on .github/workflows/deployToWordPressSVN.yml
> +    - "*"
Update this to specifically run ONLY on Stable Releases (Not drafts and not tags).

2024-02-12 13:48 UTC, MattGibney commented on .github/workflows/deployToWordPressSVN.yml
> +        SLUG: code-syntax-block
That's not our slug

2024-02-12 13:48 UTC, MattGibney commented on .github/workflows/deployToWordPressSVN.yml
> +        npm run build
This repo doesn't have any NodeJS. There are no deps to build.

2024-02-14 09:15 UTC, orssich approved these changes

2024-02-14 09:25 UTC, MattGibney approved these changes

2024-02-14 10:15 UTC, merged